### ISSUE TITLE
MAX31856_CONFIG_REG ???

### ISSUE THREAD

**Issue by AnHardt** [adafruit/Adafruit_MAX31865#15]
I know - this library is to abstract the #defines for the registers and bits in the registers away - the user should not need to use them.
However, the names for that should have the right IC-name in it.
All "MAX318**56**\_\*" have to be replaced by "MAX318**65**\_\*"
Here we are not dealing with the "MAX318**56** Precision Thermocouple to Digital Converter
with Linearization" but the "MAX318**65** RTD-to-Digital Converter".

And if the #defines are not thought to be used outside the library, should they be exported by the .h-file, or kept secret in the .cpp-file?

**Comment by caternuson** [comment]
Fixed with #30
