### ISSUE TITLE
Intermittent wrong results since V1.2.1

### ISSUE THREAD

**Issue by lubasi01** [adafruit/Adafruit_MAX31865#24]
In my project I am using 6 MAX31865 boards on an ESP32 TTGO T1 for temperature measurements.
The IDE I am using is Arduino 1.8.12.
After updating Adafruit_MAX31865 library to version 1.2.1 I get intermittent (about every 2000th measurement) wrong readings.
Wrong means up to +/-5 degrees offset.
When switching back to version 1.1.0 everything is fine.
![grafik](https://user-images.githubusercontent.com/68462034/87849288-9ae63480-c8e7-11ea-9dcd-0cdfcf1e48c8.png)
(Graph shows just a sample of the measured values)

Any idea what could be wrong?

**Comment by caternuson** [comment]
Make sure all your libraries and Board Support Packages (ESP32) are up to date. If the problem continues, please post about this in the forums with photos and details about your setup and code being used to read the sensor.
https://forums.adafruit.com/
