### ISSUE TITLE
0x40 fault

### ISSUE THREAD

**Issue by puhycz** [adafruit/Adafruit_MAX31865#4]
I try demo with Arduino Nano and it´s print only 0x40 fault. 

RTD value: 0
Ratio = 0.00000000
Resistance = 0.00000000
Temperature = -242.02
Fault 0x40
RTD Low Threshold

Please what it s mean?

Thanks,

Jan

**Comment by ladyada** [comment]
probably a wiring issue. if you purchased from adafruit you can post in our forums for tech support! :)

**Comment by SanjayChakrapani** [comment]
If you are using 3wired PT100, 
1.make sure that you cut 2-way jumper pad 
2.short the right-side pads together
3.also short 2/3 wire pad
4. **thermo.begin(MAX31865_3WIRE);**
![max31865-3wire](https://user-images.githubusercontent.com/10185212/94900304-64659200-04b2-11eb-84ed-3d20664897a3.JPG)
https://learn.adafruit.com/adafruit-max31865-rtd-pt100-amplifier/rtd-wiring-config#3-wire-sensors

**Comment by SanjayChakrapani** [comment]
> 
> 
> I try demo with Arduino Nano and it´s print only 0x40 fault.
> 
> RTD value: 0
> Ratio = 0.00000000
> Resistance = 0.00000000
> Temperature = -242.02
> Fault 0x40
> RTD Low Threshold
> 
> Please what it s mean?
> 
> Thanks,
> 
> Jan

If you are using 3wired PT100, 
1.make sure that you cut 2-way jumper pad 
2.short the right-side pads together
3.also short 2/3 wire pad
4. **thermo.begin(MAX31865_3WIRE);**
![max31865-3wire](https://user-images.githubusercontent.com/10185212/94900304-64659200-04b2-11eb-84ed-3d20664897a3.JPG)
https://learn.adafruit.com/adafruit-max31865-rtd-pt100-amplifier/rtd-wiring-config#3-wire-sensors
