### ISSUE TITLE
Using Adafruit Feather M0 with RFM95 LoRa Radio

### ISSUE THREAD

**Issue by kkalbaugh** [adafruit/Adafruit_MAX31865#6]
I am totally stumped as to why I'm unable to get this module to work with a M0.    I can take the same module move it back to Arduino Uno and it works fine.   I'm using the standard example and changing
`Adafruit_MAX31865 max = Adafruit_MAX31865(10, 11, 12, 13);`
to
`Adafruit_MAX31865 max = Adafruit_MAX31865(12,23,22,24);`

Unfortunately, I get this:

`RTD value: 0
Ratio = 0.00000000
Resistance = 0.00000000
Temperature = -242.02`

![max31865_featherm0](https://user-images.githubusercontent.com/5058905/34792664-c3d01aec-f616-11e7-9162-c64a49a85444.jpg)

I also tried swapping pin 23 & 22 incase I misunderstood the MOSI MISO stuff.

**Comment by ladyada** [comment]
hiya for tech support please post in the forums!
