### ISSUE TITLE
wrong readings

### ISSUE THREAD

**Issue by ajinkyaw** [adafruit/Adafruit_MAX31865#9]
I am using PT100 (3 Wire) to measure the temperature. 
I have connected everything perfectly.
Configuration in the code i am using is :
     `max1.begin(MAX31865_3WIRE);`

And the output is:
**output**
RTD value: 0
Ratio = 0.00000000
Resistance = 0.00000000
Temperature = -242.02

I am testing it in a room temperature.
My question is , is there any settings or calibration that i need to do, or any other way to test the PT100 sensor, because the temperature is showing correct readings.

**Comment by ladyada** [comment]
nope sounds like a wiring issue - please post in the tech support forums of the place you purchased it from. thanks :)
